### ISSUE TITLE
the last value in `layer_sizes`?

### ISSUE THREAD

**Issue by JiaqiLiu** [seba-1511/lstm.pth#2]
https://github.com/seba-1511/lstms.pth/blob/9e4da34227d6d74c4ed5233a309f78a95b9d852b/lstms/container.py#L29

Hi, may I know why we do not use the last value in `layer_sizes`?

Thanks!

**Comment by seba-1511** [comment]
https://github.com/seba-1511/lstms.pth/blob/9e4da34227d6d74c4ed5233a309f78a95b9d852b/lstms/container.py#L35

Thanks for your question. That's because we want to disable dropout on the last layer.

There is indeed a bug but it's on line 35 (linked above), where `size` should be replace by `layer_sizes[-1]`. Fixed in 383b66f .
